name: Deploy to Render

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Render Docker Registry
        run: echo "${{ secrets.RENDER_TOKEN }}" | docker login registry.render.com -u _json_key --password-stdin

      - name: Build and push image
        run: |
          docker build -t registry.render.com/YOUR-SERVICE-ID/client ./client
          docker push registry.render.com/YOUR-SERVICE-ID/client
